SuperDARNCanada/borealis

rx_signal_processing/dsp.cu, rx_signal_processing/rx_dsp_chain.cu
=> Add beamforming

radar_control/radar_control.py, sample_building/sample_building.py
Added enough samples at the end of the written samples to account for
ssdelay.
=> Adding ssdelay samples to end of written samples

usrp_drivers/n200/n200_driver.cpp
We now use timestamps to determine where in the buffer to index next for
samples. In the case of an overflow, UHD does not return the number of
samples lost. We need to use timestamps to determine how far in the
buffer we need to move along to account the missing samples.
=> Fixing offset bug

experiment_prototype/scan_classes/averaging_periods.py, experiment_prototype/scan_classes/sequences.py, radar_control/radar_control.py
=> Python profiling 2

experiment_prototype/experiment_prototype.py, experiment_prototype/scan_classes/sequences.py, utils/protobuf/datawritemetadata.proto, utils/protobuf/processeddata.proto, utils/protobuf/rxsamplesmetadata.proto, utils/protobuf/sigprocpacket.proto
Added the protobuf for datawrite from radar_control, updated other protobufs for ease of writing files (a file for each slice_id). Updated experiment_prototype to contain slice keys necessary for data write that had not yet been added (rsep, lag_table, comment).
=> Datawrite radar control proto

brian/brian.py, testing/n200_gpio_test/parse_n200_timing.py
Ignore the code review for brian, not sure how that commit got in here.
=> Logic analyzer testing

data_write/data_write.py, utils/data_write_options/data_write_options.py
The pre bfiq data had a bug where the data was being overwritten instead
of concatenated. This has been fixed. The data dimensions and
descriptors were wrong as well and have been changed.
I added more comments and a description for the data template.
=> Fixed bugs and cleaned up comments

data_write/data_write.py
the data dimensions were wrong and have been fixed.
=> Fixed rawrf data dimensions

data_write/data_write.py
pre bfiq dimensions were wrong
=> Fixed dimensions bug

experiment_prototype/scan_classes/sequences.py, radar_control/radar_control.py, sample_building/sample_building.py, utils/protobuf/sigprocpacket.proto
So @kkotyk I'm thinking you could review my changes and merge to the dev, then make another branch with your changes in the decimation using this value, PR that into the dev branch (then I can check it out), then we can test the dev branch before PR to master. Dev branch is equivalent to master at this point.
=> First rx sample

radar_control/radar_control.py, usrp_drivers/usrp_driver.cpp
Added an exchange between radar control and the driver to fix the low
averages in first integration period.
=> Adding synchronization for low averages

usrp_drivers/usrp.cpp, usrp_drivers/usrp.hpp, usrp_drivers/usrp_driver.cpp
I moved some of the functionality into the set up of the driver and
moved some of the initial stuff into the main function. I then cleaned
up some of error handling, naming, and storage of certain members.
=> Simplified and refactored the driver

experiment_prototype/experiment_prototype.py, radar_control/radar_control.py
The experiment_name was not being placed in the files.
=> Experiment_name placed in files experiment_string

data_write/data_write.py, experiment_prototype/experiment_prototype.py, radar_control/radar_control.py, utils/protobuf/datawritemetadata.proto, utils/protobuf/processeddata.proto
If you want to have all units in base SI, we should discuss because that will change some field types from ints as well.
=> Dev updated data fields

scheduler/email_utils.py, scheduler/scd_utils.py
Merging first scheduling PR changes
=> Scheduling

rx_signal_processing/dsp.cu, rx_signal_processing/dsp.hpp, rx_signal_processing/rx_dsp_chain.cu, utils/protobuf/sigprocpacket.proto
I changed the lag indexing to account for the time to next lag in terms
of samples while indexing the correlations array.
=> Fixed the lag indexing for acfs

scheduler/email_utils.py, scheduler/local_scd_server.py, scheduler/scd_utils.py
updated scheduling 2 with changes from first scheduling PR #111
=> Scheduling 2

scheduler/remote_server.py, scheduler/schedule_modifier.py
=> Scheduling 4

install_radar_deps_opensuse.sh, site_scons/site_config.py, site_scons/site_init.py
I updated Scons to be python3 compatible. I added an automatic GPU flag
detection function and I also updated the installation script to install
the latest version of armadillo.
=> Updating installation stuff

data_write/data_write.py, utils/post_processing/backconvert_borealis.py, utils/post_processing/restructure.py, utils/post_processing/restructure_borealis.py
Restructuring of pre-bfiq, bfiq and rawacf Borealis hdf5 files makes the files smaller, faster to read, and easier to use.
=> Restructure by night

config.ini, experiment_prototype/scan_classes/sequences.py, experiments/impttest.py, radar_control/radar_control.py, usrp_drivers/usrp_driver.cpp, utils/protobuf/driverpacket.proto
I added the impt test and made some fixes from previous commits to get
running
=> Adding impt

scheduler/remote_server.py
Remote server was not detecting file changes. I had to explore the
inotify triggers that nextcloud was generating and updated the code to
handle them.
=> Fixing issue with remote server

radar_control/radar_control.py, sample_building/sample_building.py
phases were looking in opposite azimuthal dir
=> RX beamforming bug fix

scheduler/local_scd_server.py
Updating special time to account for "RBSP" tag as well as [ALL] lines
Not tested. Will need to wait for new SCD file to be released, but this should account for the changes. These changes will also have to be added to the ROS scheduler too.
=> Special time changes

scheduler/remote_server.py
Fixing bug where if the first relevant time had more than one item at
that time, it would not properly find the infinite duration line.
=> Fixing relevant lines bug

borealisscreenrc
The windows now list time and system load. There is also a bar that
indicates what window is highlighted.
Can now move regions using ctrl and arrow keys to navagate windows. The
window can also respond to mouse clicks and can select regions that way
too.
=> Adding some useful enhancements

install_radar_deps_opensuse.sh
=> Added to install script for testing, file convert

docs/source/conf.py
Okay this PR should fix the missing config issue for the docs on RTD. To fix this locally, just create the symbolic link to the config file locally.
=> Rtd config fix

experiments/listening_normalscan_1.py, experiments/listening_normalscan_2.py, experiments/normalscan.py, experiments/politescan.py, experiments/politescan2.py, radar_control/radar_control.py
three new modes added:
* listening normalscan 1, with listening integration time at end of scan.
* listening normalscan2, with listening integrations of a separate frequency simultaneous with normalscan slice, looking in offset beam direction.
* politescan2, with 2 frequencies listening simultaneously in same beam directions
Also, corrected normalscan CPID.
=> Quiet modes

experiment_prototype/scan_classes/sequences.py
Some changes to remove whitespace as well. Line 462 of sequences.py is only change.
@kevinkrieger @kkotyk could one of you merge this today?
=> Remove repeated sample numbers in blanked_samples

experiments/interleavedscan.py, experiments/listening_normalscan_1.py, experiments/listening_normalscan_2.py, experiments/normalscan.py, experiments/normalscan_13MHz.py, experiments/normalscan_boresite.py, experiments/normalscan_single_beam.py, experiments/superdarn_common_fields.py, experiments/twofsound.py
To reduce noise via SuperDARN-SuperDARN interference
=> Offseting frequencies at various sites

scheduler/remote_server.py
K I think this works simpler and I think it for sure forces an inf dur line to be first.
=> Testing a fix for missing inf dur line

start_radar.sh, stop_radar.sh
Resolves #183 with some start and stop logs for human intervention to help with downtime logging.
tested on Saskatoon Jul 3 2020
=> Start stop logs

experiments/epopsound.py
Update to use kwargs and make sure center freqs will be aligned to user
requests.
=> Updates to epopsound using kwargs

experiments/IB_collab_mode.py, experiments/epopsound.py, experiments/epopsound_one_beam.py, tools/testing_utils/experiments/experiment_unittests.py
Had to modify experiment unittests because one test is no longer valid
Will pull this at Saskatoon site to run over the weekend/next week during the IBcollab run Oct 26-28
=> IBcollabmode updated for kwargs

steamed_hams.py
verified rawrf - producing modes run, updated 'testdata' mode to produce the txdata (requires python debug) as well as rawrf data outputs, but still otherwise in release mode to improve performance marginally. Added to usage message and comments
=> Steamed hams update

docs/source/setup_hardware.rst, docs/source/system_specifications.rst
Docs built and tested locally and they work.
Feel free to merge if you see no glaring errors.
=> Formatting fixes, added section on networking the Octoclocks.

data_write/data_write.py, radar_control/radar_control.py, rx_signal_processing/dsp.py, rx_signal_processing/rx_signal_processing.py, steamed_hams.py, usrp_drivers/usrp_driver.cpp, utils/protobuf/datawritemetadata.proto, utils/signal_processing_options/signal_processing_options.py
Draft PR for testing and to see differences to resolve issues - don't merge rn
=> Other sigpy

experiments/twofsound.py
Adding kwargs so that we can change the frequencies for ep495 tests
=> Quick patch for twofsound to add kwargs

steamed_hams.py
Adds the realtime screen to display by default when running borealis. Useful for debugging.
=> Added realtime window to borealis screen.

docs/source/bfiq.rst, docs/source/failure_modes.rst, docs/source/setup_software.rst
- Added several failure modes related to setting up Borealis.
- Added configuration steps for realtime_address field and how to verify correct setup.
=> Additions and clarifications to software_setup and failure_modes

experiments/superdarn_common_fields.py
requested by Pasha.
Verified freqs are not in any restricted ranges
=> Change polardarn upper freqs to be closer to lower freq - 

scheduler/local_scd_server.py
using twofsound as normal mode unless noswitching is specified.
=> Changed the default schedule to be consistent across all sites

experiments/normalsound.py
Modified the interleavesound program to create this one. Tested it on sas around 21:10-21:15 today, it goes through the 48 seconds of normalscan, then it does sounding for 8 int periods before moving onto the next scan, where it will continue with the sounding after normalscan is done.
=> Normalsound

data_write/data_write.py
Fixes incorrect median averaging and replaces cluttered lag0 samples with non-cluttered samples from alternate lag0.
=> Median avg

data_write/data_write.py
* Calculates sample number when second pulse in sequence occurs, and replaces all later samples with alternate lag0 data for those ranges.
* This has already been added to develop branch (from pull request with branch median_avg), but it is desirable to add it to master branch to ensure this change is enacted as soon as possible at operating radars.
=> Added lag0 replacement to data_write.py for writing correlations.

data_write/data_write.py
* 'correlation_dimensions' being referenced before assignment
=> Bugfix in find_expectation

experiments/widebeam_2tx.py
* Transmits only on antennas 7 and 8
* Produces antennas_iq data only
* Only uses one beam (since radiation pattern spans the FOV)
* Uses standard settings for all other parameters.
=> Created new experiment widebeam_2tx.py

data_write/data_write.py, experiment_prototype/scan_classes/sequences.py, radar_control/radar_control.py, rx_signal_processing/SConscript, rx_signal_processing/dsp.cu, rx_signal_processing/dsp.hpp, rx_signal_processing/dsp.py, rx_signal_processing/rx_dsp_chain.cu, rx_signal_processing/rx_signal_processing.py, steamed_hams.py, utils/protobuf/datawritemetadata.proto, utils/protobuf/sigprocpacket.proto
Tested against borealis_postprocessors, both Python and C++ implementations agree within numerical error.
=> Pulse phase offsets

install_radar_deps.py, utils/experiment_options/experimentoptions.py
For when the new hdw.dat format is implemented.
See https://github.com/SuperDARN/hdw/pull/5
=> Changes to reflect new hdw.dat format and repo.

install_radar_deps.py
* Linked files were linking to /usr/local/hdw.dat/ instead of
/usr/local/hdw/
=> Fixed bad reference in install_hdw_dat().

data_write/data_write.py, docs/source/config_options.rst, experiment_prototype/experiment_prototype.py, experiment_prototype/scan_classes/sequences.py, radar_control/radar_control.py, rx_signal_processing/dsp.cu, rx_signal_processing/dsp.hpp, rx_signal_processing/rx_dsp_chain.cu, sample_building/sample_building.py, usrp_drivers/usrp.cpp, utils/data_write_options/data_write_options.py, utils/driver_options/driveroptions.cpp, utils/driver_options/driveroptions.hpp, utils/experiment_options/experimentoptions.py, utils/protobuf/processeddata.proto, utils/protobuf/sigprocpacket.proto, utils/signal_processing_options/signalprocessingoptions.cpp, utils/signal_processing_options/signalprocessingoptions.hpp
This pull request is for making the distinction between physical antennas in the radar array and virtual antennas in the borealis software. The purpose of this is for situations where a subset of the array is used, such as when an N200 device goes down and a replacement cannot be made.
=> Missing n200

docs/source/setup_hardware.rst
Added LED installation guide, various other updates to hardware setup section of ReadTheDocs
=> Updated ReadTheDocs hardware setup

tools/NEC/nec_sd_generator.py
Implemented beam broadening using method of Kinsey (1997) and Leifer (2016). 
Example of the results:
=> Nec beamspoiling

tools/dsp_testing/rx_signal_processing_tests/rx_signal_processing_testing.py
Created test script for DSP functions in Python. Generates some input samples (for a typical sequence), then saves them, the filter taps, and all the stages of filtered+decimated data to a single hdf5 file.
=> Python DSP testing

docs/source/setup_software.rst, install_radar_deps.py, realtime/realtime.py
* These changes were already made in main branch, but should have been made to develop branch too.
* Removed step in setup_software.rst that was redundant as it is executed in install_radar_deps.py
=> Changes to use pydarnio for realtime module.

utils/shared_macros/shared_macros.py
Added YYYYmmdd to log timestamps so multi-day files will be more clear.
=> Improved logfile timestamps

experiment_prototype/scan_classes/sequences.py, experiments/full_fov_15km.py, experiments/full_fov_comparison.py, experiments/superdarn_common_fields.py
1. 15km Full FOV experiment for Dan
2. Full FOV comparison experiment - runs on 16 antennas with one slice, 8 antennas with the other, and uses AVEPERIOD interfacing.
=> Adding two experiments

experiments/epop2023.py
* By request of Dr. Kuldeep Pandey
=> Created experiment for EPOP collaboration Feb. 2023

src/experiment_prototype/experiment_slice.py, tests/experiments/experiment_unittests.py
* Minor bugfixes to experiment_unittests.py as well that arose when testing the changes.
Closes #426
=> Remove restriction on max number of range gates.

src/utils/log_config.py
This PR fixes exception logging after #446, so stack traces are correctly formatted.
* Outstanding issue: Exception formatting in conversion of JSON-rendered logs to console-rendered logs is broken. This will likely take a complicated, hacky fix to get working, and so it left for future development.
=> Fixed VerboseLogger definition so exceptions are formatted nicely.

docs/source/failure_modes.rst, docs/source/realtime.rst
Some minor documentation updates to clarify the purpose of the `realtime` module.
=> Adding documentation for realtime and updating failure modes.

docs/source/setup_software.rst, pyproject.toml, scripts/install_radar_deps.py
Use the dependencies specified in `pyproject.toml` to install the necessary Python packages for `install_radar_deps.py`.
=> Install python deps from pyproject.toml

src/data_write.py, src/experiment_prototype/experiment_prototype.py, src/experiment_prototype/experiment_slice.py, src/experiment_prototype/interface_classes/sequences.py, src/radar_control.py, src/utils/message_formats.py
* Calculates the `rx_sample_rate` field from the DecimationScheme object, for inclusion in files.
=> Fixing `rx_sample_rate` field

docs/requirements.txt, pyproject.toml, scheduler/local_scd_server.daemon, scheduler/local_scd_server.py, scheduler/local_scd_server.service, scheduler/remote_server.py, scheduler/scd_utils.py, src/experiment_prototype/experiment_slice.py, tests/scheduler/test_scheduler.py
Also created a daemon for running `local_scd_server.py`
* All scheduler unit tests passing.
=> Created dataclass for representing schedule entries.

README.md, docs/source/scheduling.rst, docs/source/setup_hardware.rst, docs/source/setup_software.rst, docs/source/starting_the_radar.rst, scripts/install_radar_deps.py
Updated the software setup documentation page on ReadTheDocs.
Changes:
----
- Added more specific info on Nvidia and CUDA driver installation
- Organized similar steps into sections
- Added detail and examples for installing and verifying NTP and PPS installations
- Other small changes to reflect changes we've made to Borealis over the years
See the documentation here: https://borealis.readthedocs.io/en/docs-ntp_update/source/setup_software.html
=> Software setup documentation update

src/data_write.py, src/experiment_prototype/experiment_slice.py, src/experiment_prototype/interface_classes/averaging_periods.py, src/experiment_prototype/interface_classes/interface_class_base.py, src/experiment_prototype/interface_classes/scans.py, src/experiment_prototype/interface_classes/sequences.py, src/radar_control.py, src/rx_signal_processing.py
Created new `CFSAveragingPeriod` subclass of `AveragingPeriod`, that contains the additional data necessary for clear frequency search.
=> Cfs refactor

src/radar_control.py, src/utils/signals.py
Slight restructuring of the pulse phase offset calculation.
=> Pulse offset corr

src/experiment_prototype/experiment_utils/decimation_scheme.py
This filter scheme is the same one used in the filter notebook. It uses GPU resources more efficiently, at the expense of some small side lobes (around 140 dB down from the main lobe). Notably, it is much faster, taking around 10 ms to filter the main array samples on a site computer, compared to 22-ish ms using the default 4-stage filter.
=> Use new two-stage filter as default DecimationScheme

scripts/steamed_hams.py
See #469 for motivation. I took the liberty of combining some runtime modes (`engineeringdebug` and `filterdata`) which were identical.
=> Replace cuda-gdb with gdb in steamed_hams.py

scheduler/remote_server.py, scheduler/scd_utils.py, scripts/start_radar.sh, scripts/steamed_hams.py, tests/scheduler/test_scheduler.py, tests/simulators/steamed_sham.py
* Refactored remote_server.py schedule resolution
* Added tests for schedule resolution
* More rigorous screen killing in steamed_hams.py
=> Remote server refactor

scripts/steamed_hams.py, src/usrp_driver.py
* Handles the situation where the C++ logging statement is incomplete when caught by the Python process, logging gracefully instead of crashing the process.
=> Fix usrp_driver logging errors
