SuperDARNCanada/borealis

config.ini
utils/driver_options/driveroptions.cpp
utils/driver_options/driveroptions.hpp
utils/signal_processing_options/signalprocessingoptions.cpp
utils/signal_processing_options/signalprocessingoptions.hpp

I created config options for interprocess socket connections so that the addresses can be grouped in a common place. This will let people easily change the transport protocol or ports if need be.

Moved the zmq socket addresses to config file

---

testing/octoclock_test/SConscript
testing/octoclock_test/octoclock_test.cpp

new small test code for octoclocks. Currently hardcoded 3 ip addresses.
Queries and prints all information available from octoclocks, including nmea sentences.
Note that the update_delay is very rough, as there is delay in querying the octoclock gps information
usage: ./octoclock_test --help

Octoclock testing

---

rx_signal_processing/dsp.cu
rx_signal_processing/dsp.hpp
rx_signal_processing/rx_dsp_chain.cu
utils/signal_processing_options/signalprocessingoptions.cpp
utils/signal_processing_options/signalprocessingoptions.hpp

As part of the modified Frerking filtering translation, the phase term pulled out of filtering needs to be multiplied by the output samples. This pull request addresses this.
This PR also adds in the calculation to drop samples if they may introduce edge effects from using 0 padded values that are used if the filter extends past the length of the input samples.

Added phase correction and sample dropping

---

config.ini
experiment_prototype/experiment_prototype.py
utils/experiment_options/experimentoptions.py

The USRP can only be tuned in steps of the master clock rate / 2^32.
This code adjusts for that in the experiment prototype so that samples
are correct generated at the right frequency.

Handling USRP center frequency offsets

---

experiment_prototype/scan_classes/sequences.py
radar_control/radar_control.py
rx_signal_processing/rx_dsp_chain.cu
sample_building/sample_building.py
utils/protobuf/sigprocpacket.proto

sending first_rx_sample_time instead of sample index in case rx rate
differs from tx rate.

Fix in case tx rates and rx rates differ

---

usrp_drivers/usrp_driver.cpp

Through rolling back commits, it became obvious that the broken looking
channels were not being tuned. I tracked the bug down to the rx channels
being tuned using the tx channels.

Fixing tuning issue

---

radar_control/radar_control.py
sample_building/sample_building.py
utils/experiment_options/experimentoptions.py

To be applied during beamforming. The centre offset along the array is
now accounted for in the interferometer beamforming (intf is beamformed
with the same phases as antennas 6,7,8,9 in main array in the Saskatoon
configuration). This did not work for all cases (sites) previously.
There was also a bug in how the centre was being calculated in the
get_phshift function, now fixed.

Adding in code for intf offset

---

brian/brian.py
data_write/data_write.py
rx_signal_processing/dsp.cu
rx_signal_processing/dsp.hpp
rx_signal_processing/rx_dsp_chain.cu
utils/zmq_borealis_helpers/socket_operations.py
utils/zmq_borealis_helpers/zmq_borealis_helpers.cpp

Fixign the issues where dsp threads would land up accessing the socket
at the same time causing an error. I eliminate this issue by creating
unique sockets with unique identities in each thread. For this to work i
needed to create a new recv method to receive from any identity. I then
append the sequence num to each sender iden to keep them unique.
The problem here is this means that sequences may finish out of order.
For that reason, I added logic to make sure that sequences get ordered
correctly.
I had to rework the router a bit too. We land up sending to identities
that dont exist yet, and this landed up blocking the code. I had to
rework this to queue up frames to send so they dont block other frames
that need to move through the system.

Eliminating zmq assertion error

---

scheduler/remote_server.py
scheduler/scd_utils.py

SCD code was not properly locating the last line in the scd file if the
current date was ahead of any lines in the schedule.

Fixing bug that happens when searching in scd

---

experiment_prototype/experiment_prototype.py

I _think_ this is all that's required, I couldn't find any other references to calculations for max and min frequencies.
If you two think there's a better way, let me know. Also if you think I shouldn't use a global, let me know. I think this should go to master ASAP to avoid any funky waveforms.

Quick fix to avoid edges of our tx/rx bandwidths. See Issue #195

---

site_scons/site_config.py

I noticed that cuda code was not being compiled with optimization.
Should add some speed increases for when that matters

Adding O3 for nvcc compilation in release

---

experiment_prototype/experiment_prototype.py
experiment_prototype/scan_classes/sequences.py

- num_ranges time is based on pulse_len, not output_rx_rate
(although they will have the same result if acfs is True because
in that case we force pulse_len = 1/output_rx_rate)
- updated comment on num_ranges to clarify this

Modifying ssdelay calculation

---

scheduler/remote_server.py

Bug where schedule wouldn't build properly if only a single
line of infinite duration should run

Fix for only single line of inf duration

---

radar_control/radar_control.py

are not aligned. The scan flag should only be set when
the scan is on its first aveperiod object, and the
aveperiod is on its first beam. This is the first
integration period from the scan object that will be
run.

Scan_flag fix for when scanbound and beamorder

---

data_write/data_write.py
radar_control/radar_control.py

This PR was tested via the test setup at the lab, it appears to run fine (visually inspecting log files) for all RCPs tested (twofsound, normalscan, interleavesound, etc)
Add more informative message to data write (note that slice_id and data format are not available at that point in the code)
radar_control.py:
Added debug statements
PEP8 standards applied (mostly) where it made sense.
small fix to scan start times as proposed by Marci
Added todo statements for future checks to negative times
Move num_sequences and time_remains initializations to just above where they are used
removed redundant if scan_iter == scan.num_aveperiods_in_scan (it's checked in the while loop just above it)

scan start fix

---

docs/source/setup_software.rst

Instead of installing pyDARN, install pyDARNio since Borealis only needs the reading/writing datafiles functionality.

Changes to Software Setup instructions for pyDARN + dependencies.

---

data_write/data_write.py

Small fix, just ignore the warning. A discussion on the reason for the warning can be found here: https://stackoverflow.com/questions/58414068/how-to-get-rid-of-naturalnamewarning

Suppressed NaturalNameWarning when writing hdf5 files.

---

docs/source/building_an_experiment.rst
experiments/superdarn_common_fields.py
utils/experiment_options/experimentoptions.py

Modify the standard 16 beam angles to utilize the hdw.dat file's values (typically 3.24 degrees) instead of hard-coded 3.5 degree azimuth beam separations.
This should be be tested and merged at the same time that the superdarn hdw.dat file repository is updated to add lines for when the beam separation was 3.5 degrees

Modify the standard 16 beam angles 

---

rx_signal_processing/dsp.py
rx_signal_processing/rx_signal_processing.py

* Correlations should now be identical to Borealis v0.5 calculations.
* Swapped main and intf data inputs when calculating xcfs

Changed conjugation order in correlating.

---

experiment_prototype/scan_classes/sequences.py
experiments/multifreq_widebeam.py
sample_building/sample_building.py

* Fixed small bug with type errors in the protobuf packet
* Fixed power splitting issue when the slices don't use the same antennas.
This branch has been tested with the new experiment on our lab setup and works as expected. There are two different frequencies operating each on their own set of antennas (N200s) with no power splitting as the antenna groups are mutually exclusive. I also tested the case when the antenna groups were not mutually exclusive, and the power was correctly split for all slices.

Multifreq widebeam

---

docs/source/building_an_experiment.rst
experiment_prototype/experiment_prototype.py
experiment_prototype/scan_classes/averaging_periods.py
experiment_prototype/scan_classes/scan_class_base.py
experiment_prototype/scan_classes/scans.py
experiments/2multifsound.py
experiments/epopsound_one_beam.py
experiments/fullscanstepmode.py
experiments/interleavesound.py
experiments/listening_normalscan_2.py
experiments/politescan2.py
experiments/testing_archive/2multifsound.py
experiments/testing_archive/test_bad_interfacing.py
experiments/testing_archive/test_slices_beam_order_bad.py
experiments/testing_archive/test_slices_intn_bad.py
experiments/testing_archive/test_slices_intt_bad.py
experiments/testing_archive/test_slices_scanbound_bad.py
experiments/testing_archive/test_too_many_slices.py
tools/testing_utils/experiments/experiment_tests.csv

Refactored the interfacing type names, based on [#302](https://github.com/SuperDARNCanada/borealis/issues/302)
Interfacing types have been changed from:
* SCAN -> SCAN (no change)
* INTTIME -> AVEPERIOD
* INTEGRATION -> SEQUENCE
* PULSE -> CONCURRENT
Additionally, I made some changes in documentation to standardize 'averaging period' as the standard term instead of 'integration time'.

Interfacing refactor

---

experiment_prototype/experiment_prototype.py
experiment_prototype/scan_classes/sequences.py
experiments/normalscan.py
radar_control/radar_control.py
usrp_drivers/usrp_driver.cpp
utils/protobuf/driverpacket.proto

Changes to enable aligning the start of the first pulse in a sequence to exact tenths of a second.
* Specify `'align_sequences': True` in a slice when creating your experiment to enable this functionality.
* Tenths of a second should be fine for most use cases, as typical 7- and 8-pulse sequences collect data for ~90 ms, so there is very little wasted time. Could explore modifying this in the future for sequences with considerably different timing characteristics.
* Need to test with two separate systems to see if the sequences are indeed locked in time. 
* Should be merged after #327 
Timestamps from testing on labborealis machine show that the sequences are synchronized with 10ths of a second:
```
sqn_timestamps:
1656702907.5999999046
1656702907.7000000477
1656702907.7999999523 …
```

Sequence bound

---

docs/source/antennas_iq-v04.rst
docs/source/antennas_iq-v05.rst
docs/source/antennas_iq.rst
docs/source/bfiq-v04.rst
docs/source/bfiq-v05.rst
docs/source/bfiq.rst
docs/source/rawacf-v04.rst
docs/source/rawacf-v05.rst
docs/source/rawacf.rst
docs/source/rawrf-v04.rst
docs/source/rawrf-v05.rst
docs/source/rawrf.rst

`sqn_timestamps` field in the documentation for the different versions of data files was incorrectly stated as being in milliseconds past epoch, not seconds past epoch. This PR fixes this error.

Sqn timestamps docs

---

restart_borealis.py

* Updated timestamping to be in a more readable format. Prints as YYYYMMDD.HHMM:SS, with differences shown in seconds to be easily comparable to the threshhold of 300 seconds.
Example:
```
radar@localhost:~/borealis> python3 restart_borealis.py
Write: 20220823.0000:00, Now: 20220823.0714:58, Diff: 26098.0 s
26098.0 seconds since last write
```

Added restart_borealis.py script.

---

experiment_prototype/scan_classes/sequences.py
radar_control/radar_control.py
utils/message_formats/message_formats.py

Modification of packet and message to be created inside each function they are used rather than be passed in by reference and .Clear() or .remove_*(). Also, moved debug_dict deep_copy() operation to inside the __debug__ to stop needless work in regular operations.

bug fix radar_control.py memory leak

---

experiments/narrow_wide_comparison.py

* Difficulties with EPOP timing make it advantageous for different slices to be distinguishable in some way. In this case, changing the integration time will provide a unique signature for each slice that will hopefully make it easy to identify in the EPOP data.
* Removed scanbound as slices have different integration times now.

Updated narrow_wide_comparison experiment based on advice from Don Danskin.

---

experiments/superdarn_common_fields.py

Pasha wanted the difference in common mode frequencies to be closer to 2 MHz. Some sites previously were 1.4 MHz different. Now, the differences are all between 1.7 MHz and 2.2 MHz.

Updating COMMON_MODE_FREQ_2 per Pasha's request.

---

src/data_write.py
src/usrp_drivers/utils/driveroptions.cpp

Fixes bugs preventing USRP Driver and Data Write from running when zero interferometers are configured.
Resolves https://github.com/SuperDARNCanada/borealis/issues/351, https://github.com/SuperDARNCanada/borealis/issues/355
- Added check for empty channel strings so `pop_back()` doesn't operate on empty string
- Added logic to ensure `total_recv_chs_str` has correct formatting (no commas at front or back)
- Added check for empty channel string so `make_channels_()` works correctly when no intf antennas configured

Zero interferometer USRP driver bug

---

src/experiment_handler.py
src/radar_control.py

VERY minor PR, per our confusion the other day. I looked into the code a bit more and clarified what was going on:
1. `radar_control` asks `experiment_handler` after every averaging period whether there is a new experiment to run
2. `experiment_handler` checks, and if so sends the new experiment; if not, sends `None`
3. `experiment_handler` was logging both cases as "sending a new experiment from beginning", which was misleading. Sometimes it was sending `None`
4. `radar_control` unpickles the message, and only updates the experiment if it is not `None` and inherits from `ExperimentPrototype`
5. No matter what radar_control received, it would log (at debug level) an appropriate message
The changes in this PR:
* In `experiment_handler`, only log if an actual experiment is sent. Logs at …

Changed logging for sending/receiving experiments

---

docs/conf.py
docs/requirements.txt
docs/source/utils.rst
scheduler/remote_server_options.py

- Fixed some small bugs that prevented ReadTheDocs from building cleanly
- Fixed config file parsing done within scheduler missed in recent PR
- Removed conditional within docs/conf.py that prevented certain code from running outside of ReadTheDocs
Docs successfully built on ReadTheDocs, viewable here: https://borealis.readthedocs.io/en/bugfix-missed_doc_update/

Docs build / scheduler config parsing bugfix

---

docs/conf.py
docs/requirements.txt

Previously, when building the documentation on ReadTheDocs, the entire Borealis code structure was essentially imported within ReadTheDocs. This meant that configuration options such as hdw repo location and borealis data directories had to be created on ReadTheDocs.
To get around this, I added the `utils` package to the `autodoc_mock_imports` list within `conf.py`. This prevents the ReadTheDocs build from failing when exceptions are thrown within files in the `utils` package (such as `options` and `log_config`).

Removed options and log_config dependency from ReadTheDocs

---

docs/source/scheduling.rst
scheduler/scheduler_sync.daemon

Added Slack alerts to scheduler sync daemon. Alerts trigger when scheduler fails to sync after retrying 3+ consecutive times.
Tested on my local machine to ensure logic was correct.
Currently testing for all sites.

Scheduler sync alerts

---

docs/source/starting_the_radar.rst
scripts/restart_borealis.daemon
scripts/restart_borealis.py
scripts/start_radar.sh
scripts/stop_radar.sh

This PR creates a daemon to control restart_borealis.py, allowing alerts to be sent when Borealis restarts repeatedly. Other changes are improved logging in restart/stop/start scripts and small bugfixes.
Tested the daemon and scripts individually on the lab machine. Since the lab isn't setup to start Borealis via the scheduler, I simulated starting Borealis by manually running steamed_hams. 
**Next stage:** Testing at SAS - the daemon script can be manually copied over to the computers, and should work with the scripts on `main`, so we won't need to do a release first to test.

Adding alerts to restart_borealis

---

config/cly/restrict.dat.cly
config/inv/restrict.dat.inv
config/pgr/restrict.dat.pgr
config/rkn/restrict.dat.rkn
config/sas/restrict.dat.sas

We received an email warning us that 14.00 MHz to 14.350 MHz is a HAM band and that we should add it to our restriction table. I have it for each site with a 0.205 MHz buffer (which may be excessive).
In Canada, the band is allocated exclusively for Amateur radio. The 14.250 MHz to 14.350 MHz is fixed service, which we may not interfere at some sites as we are also fixed. It all depends on pointing directions and power. The amateur are allowed 100 W ERP whereas we are allowed 1.567 kW ERP, so we would swamp them. Internationally, in some countries 14.250 MHz to 14.350 MHz is also a fixed service with a 24 dBW ERP.
Here are some helpful links:
https://www.rac.ca/rac-0-30-mhz-band-plan/
https://ised-isde.canada.ca/site/spectrum-management-telecommunications/en/learn-more/key-documents/consul …

HAM frequency restrictions

---

restrict.dat.cly
restrict.dat.inv
restrict.dat.pgr
restrict.dat.rkn
restrict.dat.sas

Restrict HAM band 14.0-14.35 MHz at all sites (plus buffer).

---

src/realtime.py

Borealis only serves beam 0 when running multi-beam experiments. It would be nicer for the website if all beams were served. There may be some down-stream ramifications due to 16x more packets being sent, but that is a problem for downstream to handle.

Serve all records in simultaneous multi-beam experiments.

---

tests/NEC/nec_sd_generator.py

Updates to the NEC generator script to increase flexibility in simulation.
**CHANGES**:
* Allow for specification of the main and interferometer reflector fence lengths. If not specified, defaults to a length suitable given the number of antennas specified in each array.
* Add an option to turn off the ground plane, for simulating the array far away from any ground plane.

Nec model options

---

scheduler/remote_server.py

This pull request fixes a small bug in remote_server.py
If the schedule file is updated consecutive times, remote_server.py will crash after updating the atq. This problem didn't come up very often, as Borealis often reboots in between schedule updates.
The problem was caused by the emailer - after sending an email after the initial schedule update, the program killed the `smtp` emailer instance. If the scheduler tried to send another email after this point, it would crash. This was fixed by re-creating an emailer instance before updating the schedule each time.

Scheduler crashing bugfix

---

.readthedocs.yaml
docs/.readthedocs.yaml
docs/conf.py
docs/requirements.txt
docs/source/setup_software.rst

ReadTheDocs for develop wasn't showing correct formatting - just raw html.
This problem was fixed by specifying an older version of `sphinx-rtd-theme` in `docs/requirements.txt`.
I also moved `.readthedocs.yaml` to the `docs/` directory, since we're allowed to do this now.

Fix ReadTheDocs formatting

---

docs/source/building_an_experiment.rst
docs/source/new_experiments.rst
src/experiment_prototype/experiment_slice.py
src/experiment_prototype/scan_classes/sequences.py

Added functionality to borealis to accept a function defined in the experiment that will return specific phases for the rx antennas when processing data to rawacf.

Rx antenna pattern

---

scripts/steamed_hams.py

To help with debugging, I've added a `tee` command for each Borealis process to capture the output printed to the Borealis screen. This will allow us to more easily view bugs in Borealis and view the output printed to the screen when Borealis crashes. 
The logs are printed to `/data/borealis_logs/[module].log`. These files will only contain the output most recently printed by Borealis, and will be overwritten each time `steamed_hams.py` runs.
This is a temporary fix, and should be improved upon in future logging improvements. Ideally, in the future this console output would be captures within our normal logs. As it currently stands though, any errors within Borealis that occur before StructLog initializes (i.e. import errors) aren't captured by our logs - thus why we need this PR.

Added capture of Borealis console output

---

config/sas/sas_config.ini
tests/experiments/experiment_unittests.py

There was a problem with `pkgutil.itermodules` where passing a Path() object worked for certain python versions, but not others. Passing a string works for all versions.
The error this bugfix fixes was:
```
Traceback (most recent call last):
File "/usr/lib64/python3.10/pkgutil.py", line 417, in get_importer
importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/radar/borealis/src/borealis_experiments')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/radar/borealis//tests/experiments/experiment_unittests.py", line 372, in <module>
run_tests(sys.argv[1:])
File "/home/radar/borealis//tests/experiments/experiment_unittests.py", line 332, in run_tests
build_experiment_tests(experiments, args.kwargs)
File …
```

Fixed bug in experiment_unittests

---

scheduler/email_utils.py
scheduler/local_scd_server.py
scheduler/remote_server.py
scheduler/scheduler_sync.daemon
scripts/restart_borealis.daemon
scripts/start_radar.sh
scripts/stop_radar.sh

This pull request makes the following changes:
- Fixes a small bug with schedule syncing
- Improves logging within local and remote server processes
- Improves start_ and stop_radar.sh
The scheduler sync daemon was having problems monitoring changes to site .scd files. The problem was due to the `borealis_schedules` directory being a NAS mounted directory, so inotify couldn't properly see file modifications. The `borealis_schedules` directory was moved to `/home/radman` instead, which appears to have fixed the problem.
I made a few other small quality of life improvements to local_scd_server.py as well.
For local_server.py:
- I removed the plotting (it wasn't useful and cluttered up the code quite a bit)
- Added printing of email messages to stdout
For start_radar.sh and stop_radar.sh I …

Scheduler quality of life update

---

src/experiment_prototype/experiment_slice.py

This PR is to address #416, ensuring that the `DecimationScheme` plays well with the `rx_bandwidth` set for the experiment.

Created validator for input rx rate matching with DecimationScheme.

---

scheduler/quick_test_scdutils.py
scheduler/remote_server.py
scheduler/scd_utils.py
tests/scheduler/test_scheduler.py

`remote_server.py` was testing thousands of schedule lines trying to determine the correct experiment to run. This PR fixes this problem by removing the offending function and fixing the function in `scd_utils.py` that was behaving incorrectly.
* `get_relevant_lines()` of `remote_server.py` was conducting a minute-by-minute search, rather than stepping through the entries of the schedule file. This function has been removed.
* `get_relevant_lines()` of `scd_utils.py` was updated to grab all future and current lines, as well as any past lines that run past the current time, and the most recent infinite-duration line from the past.
* Added in a check to ensure that infinite-duration lines have priority zero (otherwise, they would supersede any lower-priority experiments scheduled after …

Correct determination of lines to schedule

---

docs/source/experiment_prototype.rst
src/experiment_prototype/interface_classes/interface_class_base.py

* Fixes the issue described in #449
* Docs formatted slightly incorrectly due to InterfaceClassBase refactor.
* Sort in slice_combos_sorter by first slice in each combo.

Fix docs and sort interfaced slices.

---

scheduler/local_scd_server.py

local_scd_server.py was crashing after updating the schedule for a second consecutive time while running from the same process. It is crashing because the emailer kills itself after sending an email the first time the while loop is entered, but a new emailer isn't created for subsequent loops.
To fix, I moved emailer class creation within while loop so a new one is made every loop.

Fixed bug in local_scd_server.py

---

src/rx_signal_processing.py

Log a warning in the RX signal processing window if cupy is not installed.

Warn if cupy not installed

---

src/usrp_drivers/usrp_driver.cpp

Move the driver initialization message between the driver and radar control into the transmit thread of usrp_driver.cpp, instead of before the thread was initialized. This seems to fix what was probably a race condition, where radar_control would reply and the message would be sent after usrp_driver's main thread closes the socket and before the transmit thread re-opens it.

Fix for radar hanging after USRP Driver initialization on lab computer.

---

src/usrp_drivers/usrp_driver.cpp
src/usrp_drivers/utils/zmq_borealis_helpers.cpp
tests/octoclock_test/octoclock_test.cpp
tests/rx_tx_delay_test/rx_tx_delay_test.cpp
tests/test_rx_tx/test_rx_tx.cpp

Removed unused variables, updated deprecated zmq methods, and updated header include names.
Code now compiles in both release and debug mode without throwing any warnings (on the lab computer at least).

Scons warnings

---

tests/log_printer/json_to_rich_logs.py

When an error was in listed in the log file, the rich printer would crash as it was not set up to handle errors. This change just allows it to keep going and print a warning to screen that parsing an error report was skipped.

Rich Printer Crashes

---

src/experiment_prototype/interface_classes/averaging_periods.py
src/rx_signal_processing.py
src/utils/signals.py

Cupy's memory allocation methods were crashing the radar for experiments that had very high memory requests as it would try to allocate more memory than was available on the GPU. These changes are a step towards better memory management on the GPU. They ensure that the memory used after a sequence has been processed is freed before the next sequence starts. Previously cupy was allocating twice the amount of memory than was required. 
Further improvements can likely be made to the GPU memory usage, but this should help prevent experiments from overloading a GPU. Unfortunately this does add more time to the DSP processing. On the lab computer DSP took on average 10ms longer each sequence but the double memory allocation was stopped. See #260 for more cupy memory management ideas that could …

Cupy mem allocation

---

docs/source/building_an_experiment.rst
src/experiment_prototype/experiment_prototype.py
src/experiment_prototype/experiment_slice.py

Adds a method to experiment prototype to allow the experiment to determine what tx and rx center frequency to set if the parameter is not set by the user, replacing the previous default center frequencies of 12 MHz.
Center frequencies no longer need to be set by the user regardless of the chosen operating frequency. If an experiment that has an invalid set up (ie: concurrent or sequence interfacing slices that have a frequency separation greater than the tune band width of 3.5 MHz), then the experiment will fail with an exception.
Changes made to borealis_experiments accomodating these changes are in PR [#21](https://github.com/SuperDARNCanada/borealis_experiments/pull/21)

Auto center freq

---

docs/source/new_experiments.rst
src/data_write.py
src/experiment_prototype/experiment_slice.py
src/experiment_prototype/interface_classes/averaging_periods.py
src/radar_control.py
src/rx_signal_processing.py
src/utils/message_formats.py
src/utils/signals.py

Added three new cfs parameters to allow users more control over the CFS performance:
**CFS Stable Time**
- Defines a minimum time during which once a CFS slice freq is set, it will not be changed again.
- Does not force CFS to change freq after time has passed
- Defined in number of seconds
- The CFS scan and processing are not run during the stable time
**CFS Power Threshold**
- Defines a power threshold in dB that must be surpassed before CFS changes a frequency for a slice
- Case 1: Another frequency within the cfs range is found to have a power lower than the power that the current frequency was at when it was set less the threshold power
- Case 2: The currently set frequency is found to have increased in power to a value greater than the original power when set plus the threshold …

User control params for CFS

---

src/usrp_drivers/usrp_driver.cpp

If the GPS time differs from the system time by more than 1000 seconds (arbitrary choice, roughly 17 minutes), then the driver will exit with an error and our automated restart scripts will have to reboot the radar. This is to avoid bad timestamps in generated data files.

Stop radar if GPS time wrong

---

src/usrp_drivers/usrp_driver.cpp

Starts the first pulse in a pulse sequence on a clean millisecond boundary.
Closes #489

Lock first pulse in sequence to next millisecond

---

src/radar_control.py

cfs was escaping the processing block during the user defined stable time without setting the cfs_params.

Fixed not referencing correct cfs data during stable time

---

scripts/steamed_hams.py
src/data_write.py
src/experiment_prototype/interface_classes/sequences.py
src/radar_control.py
src/utils/file_formats.py
src/utils/message_formats.py
tests/simulators/steamed_sham.py

The format is used only for commissioning a Borealis system, and even so rarely. Instead, we rely on oscilloscope measurements or loopback tests to ensure that the transmitted samples are correct.

Remove `txdata` format

---

src/data_write.py

The internal `SliceData` object has an `antennas_iq_data` field that was being overwritten by each subsequent stage before the stage was written, so all stage files would have the final stage's data written.

Fixing bug of filter stage data being copies of antennas_iq data

---

src/utils/file_formats.py

Modifies file_formats.py to make some fields optional only for certain file types.
E.g. `lags` optional for antennas_iq and bfiq, but required for rawacf files.

Fixing data_write bug when acfs set to False in experiment.

---

docs/source/starting_the_radar.rst
scripts/apcupsd/offbattery
scripts/apcupsd/onbattery
scripts/start_radar.sh
scripts/stop_radar.sh

Added scripts used by `apcupsd` to start and stop the radar when during power outages.

Add APCUPSD scripts to start/stop radar during power outages

---

src/rx_signal_processing.py
src/utils/signals.py

Same issue present in borealis_postprocessors. `tau_spacing` was calculated as 7.999... , then truncated to an integer as 7 instead of 8. A similar calculation was being done for the offset to the first range, so I rounded that calculation as well before truncating.

Fixing rounding errors affecting two-stage filter mode.

---

src/data_write.py
src/experiment_prototype/interface_classes/sequences.py
src/radar_control.py
src/rx_signal_processing.py
src/utils/data_aggregator.py
src/utils/message_formats.py
src/utils/signals.py

Fixes a bug wherein Borealis would write `intf_acfs` to file if writing rawacf files, regardless of value of `acfint` in the slice definition. Similarly with `xcfs`. 
I've tested with a two-slice concurrent-interfaced experiment, toggling `acf, `acfint`, and `xcf` for one slice at a time, verifying that the fields are only written to file for the specified slices. Also, verified that rawacf files are only written when `acf` is set for a slice (if it is False, `acfint` and `xcf` are overwritten to False too, regardless of their specification in the slice definition).

Only write correlations to file if specified in slice
